language: php
php:
  - 5.4
  - 5.5
  - 5.6
services:
  - elasticsearch
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - composer update --prefer-dist
script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs -p --standard=PSR2 --ignore=vendor/,Tests/app/ ./
